# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'GymCare' do
  # Comment the next line if you don't want to use dynamic frameworks
  
  use_frameworks!
  
  # Pods for GymCare
  pod 'SVProgressHUD', '~> 2.2.5'
  pod "MomoiOSSwiftSdk", :git => "https://github.com/momo-wallet/mobile-sdk.git", :branch => "release_swift", submodules: true
  pod 'Moya', '~> 15.0'
  pod 'HGCircularSlider'
  pod 'JTAppleCalendar'
  pod 'SDWebImage'
  pod 'SwiftDate'
  pod 'TLPhotoPicker'
  pod 'Firebase/Messaging', '~> 8.14.0'
  pod 'Firebase/Core', '~> 8.14.0'
  
  post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
